name: main

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download Dependencies
        run: nix develop --command echo "Dependencies downloaded"
      - name: Render thesis
        run: nix develop --command bmake
      - name: Render corrections
        run: nix develop --command typst compile corrections.typ
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            thesis.pdf
            corrections.pdf
