@startuml
skinparam monochrome true
skinparam shadowing false
skinparam style strictuml

(B)
if (data locally available?) then (yes)
:Return data to requester;
else (no)
:Add requester to audience for data;
endif
stop

@enduml
