@startuml
skinparam monochrome true
skinparam shadowing false
skinparam style strictuml

start
while (loop while alive)
switch (request)
case ( )
:PUT /computation/*;
(A)
(D)
case ( )
:GET /data/*;
(B)
case ( )
:POST /data/*;
(C)
(D)
case ( )
:PUT /computation-ready/*;
(E)
endswitch
endwhile
-[hidden]->
detach
@enduml
