@startuml
skinparam monochrome true
skinparam shadowing false
skinparam style strictuml
skinparam LifelineStrategy nosolid
skinparam sequenceMessageAlign center
title Work Request

participant Client as client
participant Worker as worker

client -> worker ++: Request work
activate client
worker --> client: ACK
deactivate client
worker -> worker ++--: Attain arguments,\npossibly from other workers
worker -> worker ++--: Run computation
client -> worker: Result available?
activate client
worker -> client: Unavailable
deactivate client
note over client
Client may continue
other processing
in the meantime
end note
worker -> worker ++--: Store results of computation
worker -> worker --: Return to main loop
client -> worker: Result available?
activate client
worker -> client: Available
deactivate client
client -> worker ++: emerge result
activate client
return result
deactivate client
@enduml
